# Generated by Django 6.0.3 on 2026-04-04 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_producto_vendero'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='vendero',
            new_name='vendedor',
        ),
    ]
