# Generated by Django 6.0.3 on 2026-04-11 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_categoria_producto_creado_en_producto_ventas_totales_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(choices=[('CMP', 'Componentes para pc'), ('VID', 'Videojuegos'), ('TAB', 'Tabletas y portátiles'), ('TMA', 'Teclados, mouse y accesorios'), ('ALM', 'Almacenamiento de datos'), ('COM', 'Computadora y accesorios'), ('AUR', 'Auriculares y accesorios'), ('FOT', 'Fotografía e iluminación'), ('AUD', 'Audio y radio'), ('ADA', 'Adaptadores'), ('BAT', 'Baterías y accesorios'), ('OTR', 'Otros')], default='OTR', max_length=3, unique=True),
        ),
    ]
