# Generated by Django 6.0.3 on 2026-04-11 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_alter_categoria_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(choices=[('MOU', 'Mouse'), ('TEC', 'Teclados'), ('HEA', 'Headsets'), ('MIC', 'Micrófonos'), ('WEB', 'Webcams'), ('MON', 'Monitores'), ('CAS', 'Cases'), ('BAS', 'Bases Cooler'), ('SOP', 'Soportes'), ('MPA', 'Mouse Pads'), ('GAM', 'Gamepads'), ('KEY', 'Keycaps'), ('SWI', 'Switches'), ('FIG', 'Figuras'), ('CON', 'Consolas'), ('VID', 'Videojuegos'), ('SIL', 'Sillas'), ('CMB', 'Combos'), ('PRO', 'Promociones'), ('OTR', 'Otros')], default='OTR', help_text='Selecciona la subcategoría exacta del producto', max_length=3, unique=True),
        ),
    ]
